.github/workflows/validation.yaml
We need to sanitize the PR title by leveraging an environment variable as an intermediate step to prevent potential script injection attacks. This additional measure enhances the security of the workflow.
=> fix(ci): Sanitize PR title by using ENV variable

apps/wallet/src/components/permissions/IndividualAccountPermissions.spec.ts, apps/wallet/src/components/permissions/IndividualAccountPermissions.vue, apps/wallet/src/components/permissions/IndividualUserGroupPermissions.spec.ts, apps/wallet/src/components/permissions/IndividualUserGroupPermissions.vue, apps/wallet/src/components/permissions/IndividualUserPermissions.spec.ts, apps/wallet/src/components/permissions/IndividualUserPermissions.vue, apps/wallet/src/components/permissions/PermissionList.vue
This was missed during the refactor of Access Policy to permission done before the release. With this change we can again correctly filter and show the permissions in the corresponding page for selected resource entries.
=> fix(wallet): permission page shows individual resource section

apps/wallet/src/generated/control-panel/control_panel.did, apps/wallet/src/generated/control-panel/control_panel.did.d.ts, apps/wallet/src/generated/control-panel/control_panel.did.js, core/control-panel/api/spec.did, core/control-panel/api/src/common.rs, core/control-panel/api/src/lib.rs, core/control-panel/api/src/registry.rs, core/control-panel/impl/src/controllers/mod.rs, core/control-panel/impl/src/controllers/registry.rs, core/control-panel/impl/src/core/memory.rs, core/control-panel/impl/src/core/middlewares.rs, core/control-panel/impl/src/errors/registry.rs, core/control-panel/impl/src/mappers/helper.rs, core/control-panel/impl/src/mappers/mod.rs, core/control-panel/impl/src/mappers/registry.rs, core/control-panel/impl/src/models/indexes/artifact_index.rs, core/control-panel/impl/src/models/indexes/mod.rs, core/control-panel/impl/src/models/indexes/registry_index.rs, core/control-panel/impl/src/models/mod.rs, core/control-panel/impl/src/models/registry.rs, core/control-panel/impl/src/models/registry_entry.rs, core/control-panel/impl/src/repositories/artifact.rs, core/control-panel/impl/src/repositories/indexes/mod.rs, core/control-panel/impl/src/repositories/indexes/registry_index.rs, core/control-panel/impl/src/repositories/mod.rs, core/control-panel/impl/src/repositories/registry.rs, core/control-panel/impl/src/services/mod.rs, core/control-panel/impl/src/services/registry.rs, libs/orbit-essentials/src/lib.rs, libs/orbit-essentials/src/pagination.rs
This PR adds the registry api interface and repositories for the registry. I've only included some of the get implementation in the service layer for now and had to move the pagination from the station canister to the common orbit_essentials lib to be reused by the control-panel. 
Also, i'll still create a follow up PR that will remove the pagination implementation from the station canister and will start to use it from the common orbit_essentials lib.
=> feat(control-panel): add registry api interface and repository

core/station/impl/src/factories/requests/add_account.rs, core/station/impl/src/factories/requests/add_address_book_entry.rs, core/station/impl/src/factories/requests/add_request_policy.rs, core/station/impl/src/factories/requests/add_user.rs, core/station/impl/src/factories/requests/add_user_group.rs, core/station/impl/src/factories/requests/change_canister.rs, core/station/impl/src/factories/requests/create_canister.rs, core/station/impl/src/factories/requests/edit_account.rs, core/station/impl/src/factories/requests/edit_address_book_entry.rs, core/station/impl/src/factories/requests/edit_permission.rs, core/station/impl/src/factories/requests/edit_request_policy.rs, core/station/impl/src/factories/requests/edit_user.rs, core/station/impl/src/factories/requests/edit_user_group.rs, core/station/impl/src/factories/requests/manage_system_info.rs, core/station/impl/src/factories/requests/mod.rs, core/station/impl/src/factories/requests/remove_address_book_entry.rs, core/station/impl/src/factories/requests/remove_request_policy.rs, core/station/impl/src/factories/requests/remove_user_group.rs, core/station/impl/src/factories/requests/transfer.rs
This PR makes request creation asynchronous which is necessary for validation of call canister requests (to be added in a follow-up PR).
=> chore(station): make request creation asynchronous

Cargo.toml, core/control-panel/api/src/artifact.rs, core/control-panel/api/src/canister.rs, core/control-panel/api/src/common.rs, core/control-panel/api/src/manage_user.rs, core/control-panel/api/src/registry.rs, core/control-panel/api/src/user.rs, core/control-panel/api/src/user_station.rs, core/station/api/src/account.rs, core/station/api/src/address_book.rs, core/station/api/src/capabilities.rs, core/station/api/src/change_canister.rs, core/station/api/src/common.rs, core/station/api/src/external_canister.rs, core/station/api/src/metadata.rs, core/station/api/src/notification.rs, core/station/api/src/permission.rs, core/station/api/src/request.rs, core/station/api/src/request_policy.rs, core/station/api/src/resource.rs, core/station/api/src/system.rs, core/station/api/src/transfer.rs, core/station/api/src/user.rs, core/station/api/src/user_group.rs, core/upgrader/api/src/lib.rs
The types defined in the API are for external use.  These types would be considerably more useful if they were to implement `serde` serialize and deserialize traits.  An example use is the equivalent of `dfx canister call --output json` in the upcoming Orbit command line tool.
The `serde::Deserialize` trait is already derived for use with candid.  Only the `serde::Serialize` trait needs to be added.
Possible counterarguments:
- The Wasm sizes may increase.
- I tested the station canister, as that has the largest number of changed types.  The Wasm size is unchanged, even the sha256sum of the compiled Wasm is unchanged:
- Current main:
max@sinkpad:~/dfn/orbit (2:21)$ ls -lh wasms/station.wasm.gz 
-rw-rw-r-- 1 max max 1,5M Jun 18 11:20 wasms/station.wasm.gz
max@sinkpad:~/dfn/orbit (2:27)$ ls …
=> feat(api): Add the serde::Serialize trait to API types

apps/wallet/src/generated/station/station.did, apps/wallet/src/generated/station/station.did.d.ts, apps/wallet/src/generated/station/station.did.js, core/control-panel/impl/src/core/constants.rs, core/control-panel/impl/src/services/deploy.rs, core/station/api/spec.did, core/station/api/src/system.rs, core/station/impl/src/core/constants.rs, core/station/impl/src/services/system.rs, tests/integration/src/control_panel_tests.rs, tests/integration/src/setup.rs
This PR adds an optional fallback controller to the station's initial arguments (used when installing/reinstalling the station).  The control panel sets the NNS root canister as the fallback controller.
=> feat(station): optional fallback controller

apps/wallet/src/generated/station/station.did, apps/wallet/src/generated/station/station.did.d.ts, apps/wallet/src/generated/station/station.did.js, core/control-panel/impl/src/services/deploy.rs, core/station/api/spec.did, core/station/api/src/system.rs, core/station/impl/src/errors/system.rs, core/station/impl/src/factories/requests/add_account.rs, core/station/impl/src/models/request.rs, core/station/impl/src/services/account.rs, core/station/impl/src/services/request.rs, core/station/impl/src/services/system.rs, tests/integration/src/disaster_recovery_tests.rs, tests/integration/src/setup.rs, tests/integration/src/utils.rs
This PR adds the optional functionality of providing an initial set of accounts to the init args of the station canister. This feature enables the disaster recovery to restore accounts in case of `(re)install`.
=> feat(upgrader): disaster recovery recreates accounts

apps/wallet/build/main.build.ts, apps/wallet/build/plugins/with-ic-assets.plugin.ts, apps/wallet/package.json, apps/wallet/src/core/compatibility.core.ts, pnpm-lock.yaml
Removes the need for `unsafe-eval` in the CSP headers.
=> feat(wallet): remove unsafe-eval csp by bumping the agent

apps/wallet/src/components/change-canister/AdvancedUpdateMode.spec.ts, apps/wallet/src/components/change-canister/AdvancedUpdateMode.vue, apps/wallet/src/components/change-canister/ChangeCanisterActionBtn.vue, apps/wallet/src/components/change-canister/ChangeCanisterConfirmationScreen.spec.ts, apps/wallet/src/components/change-canister/ChangeCanisterConfirmationScreen.vue, apps/wallet/src/components/change-canister/ChangeCanisterForm.spec.ts, apps/wallet/src/components/change-canister/ChangeCanisterForm.vue, apps/wallet/src/components/change-canister/RegistryUpdateMode.spec.ts, apps/wallet/src/components/change-canister/RegistryUpdateMode.vue, apps/wallet/src/components/change-canister/change-canister.types.ts, apps/wallet/src/composables/change-canister.composable.spec.ts, apps/wallet/src/composables/change-canister.composable.ts, apps/wallet/src/core/compatibility.core.ts, apps/wallet/src/locales/en.locale.ts, apps/wallet/src/locales/fr.locale.ts, apps/wallet/src/locales/pt.locale.ts, apps/wallet/src/services/control-panel.service.spec.ts, apps/wallet/src/services/control-panel.service.ts, apps/wallet/src/services/station.service.ts, apps/wallet/src/stores/station.store.ts, apps/wallet/src/test.utils.ts, apps/wallet/src/utils/helper.utils.spec.ts, apps/wallet/src/utils/helper.utils.ts
Introduces a simpler way to keep up to date with station and upgrader changes by using the control panel registry.
**Relevant changes:**
- Split the change canister component into 2 modes advanced and automated
- Advanced mode allows the user to upload any wasm with the respect optional init args
- Automated mode checks for the next version against the control panel registry
- The station store upon connecting to a station and if the user has the `ChangeCanister` permission will check if a new version of the station/upgrader is available
- This early check will be used in a follow up PR to prompt the user to update in the toolbar of the app
**Automated mode:**  
**Advanced mode:**
=> feat(wallet): add advanced and automated mode to upgrades

apps/wallet/src/generated/station/station.did, apps/wallet/src/generated/station/station.did.d.ts, apps/wallet/src/generated/station/station.did.js, core/station/api/spec.did, core/station/api/src/external_canister.rs, core/station/impl/results.yml, core/station/impl/src/core/memory.rs, core/station/impl/src/core/mod.rs, core/station/impl/src/errors/external_canister.rs, core/station/impl/src/factories/requests/configure_external_canister.rs, core/station/impl/src/factories/requests/create_canister.rs, core/station/impl/src/factories/requests/mod.rs, core/station/impl/src/mappers/external_canister.rs, core/station/impl/src/mappers/mod.rs, core/station/impl/src/mappers/notification_type.rs, core/station/impl/src/mappers/request_operation.rs, core/station/impl/src/mappers/request_operation_type.rs, core/station/impl/src/models/external_canister.rs, core/station/impl/src/models/indexes/external_canister_index.rs, core/station/impl/src/models/indexes/mod.rs, core/station/impl/src/models/indexes/request_operation_type_index.rs, core/station/impl/src/models/mod.rs, core/station/impl/src/models/request.rs, core/station/impl/src/models/request_operation.rs, core/station/impl/src/repositories/external_canister.rs, core/station/impl/src/repositories/indexes/external_canister_index.rs, core/station/impl/src/repositories/indexes/mod.rs, core/station/impl/src/repositories/mod.rs, core/station/impl/src/services/external_canister.rs
This initial PR adds the implementation of the external canister management.
**The following TODOs will be added in future PRs:**
- Integrate with request policies
- Integrate with permissions
- Use the service methods in the `ExternalCanisterController`
- Add integration tests for the top up and update ic settings operations
- Implement the search leveraging the indexes
=> feat(station): add external canister management

apps/wallet/src/generated/station/station.did, apps/wallet/src/generated/station/station.did.d.ts, apps/wallet/src/generated/station/station.did.js, core/station/api/spec.did, core/station/api/src/external_canister.rs, core/station/impl/results.yml, core/station/impl/src/controllers/request_policy.rs, core/station/impl/src/factories/requests/add_request_policy.rs, core/station/impl/src/factories/requests/edit_request_policy.rs, core/station/impl/src/factories/requests/remove_request_policy.rs, core/station/impl/src/mappers/request_operation.rs, core/station/impl/src/models/request_operation.rs, core/station/impl/src/repositories/indexes/request_policy_resource_index.rs, core/station/impl/src/repositories/request_policy.rs, core/station/impl/src/services/account.rs, core/station/impl/src/services/external_canister.rs, core/station/impl/src/services/request_policy.rs, core/station/impl/src/services/system.rs, tests/integration/src/external_canister_tests.rs
This PR integrates the request policies with the external canisters.
**Note:** i've also removed the async need in the request policy service methods.
=> feat(station): integrate request policies and external canisters

apps/wallet/src/generated/station/station.did, apps/wallet/src/generated/station/station.did.d.ts, apps/wallet/src/generated/station/station.did.js, core/station/api/spec.did, core/station/api/src/external_canister.rs, core/station/impl/src/mappers/external_canister.rs, core/station/impl/src/mappers/request_operation.rs, core/station/impl/src/models/external_canister.rs, core/station/impl/src/models/request_operation.rs, core/station/impl/src/services/external_canister.rs
The external canister policies were sharing the same type, this was not accurate in the case of a get operation, because this allowed a rule to be returned with an optional `policy_id` which could never happen.
This update separates those types.
=> feat(station): use different types for input and get of external canister policies

core/station/impl/src/controllers/notification.rs, core/station/impl/src/services/notification.rs
This PR removes notification access checks in the notification service since the access checks are now performed early in the authorization middleware (cf. https://github.com/dfinity/orbit/pull/323).
=> chore(station): remove fn assert_notification_access

core/control-panel/impl/src/controllers/http.rs, tests/integration/src/http.rs
This PR adds candid decoding quota to `http_request` endpoint of the control panel canister. This way, excessively large HTTP requests are rejected early.
=> chore(control-panel): introduce candid decoding quota for http_request

apps/wallet/src/generated/control-panel/control_panel.did, apps/wallet/src/generated/control-panel/control_panel.did.d.ts, apps/wallet/src/generated/control-panel/control_panel.did.js, core/control-panel/api/spec.did, core/control-panel/api/src/canister.rs, core/control-panel/impl/src/services/canister.rs, orbit, scripts/deploy.sh, tests/integration/src/control_panel_tests.rs, tests/integration/src/setup.rs, tests/integration/src/utils.rs
This PR refactors the `upload_canister_modules` of the control panel to allow uploading the station and upgrader separately so that they don't have to jointly fit into the ingress message size limit of 2MiB on application subnets.
=> chore(control-panel): upload station and upgrader separately

core/station/impl/src/jobs/execute_scheduled_requests.rs, core/station/impl/src/repositories/request.rs
This PR bounds the maximum number of processing requests to 400. Having more than 500 processing requests could lead to spurious failures since the queue capacity between any pair of canisters is 500 and thus, e.g., there cannot be more than 500 ICP ledger transfers processing concurrently. With a value of 400, we also leave some slack.
=> fix(station): bound the maximum number of processing requests

apps/wallet/src/components/external-canisters/CanisterSetupDialog.vue, apps/wallet/src/generated/station/station.did, apps/wallet/src/generated/station/station.did.d.ts, apps/wallet/src/generated/station/station.did.js, apps/wallet/src/pages/ExternalCanisterDetailPage.vue, core/station/api/spec.did, core/station/api/src/external_canister.rs, core/station/impl/src/errors/external_canister.rs, core/station/impl/src/errors/request.rs, core/station/impl/src/errors/request_policy.rs, core/station/impl/src/errors/validation.rs, core/station/impl/src/mappers/request_operation.rs, core/station/impl/src/migration.rs, core/station/impl/src/models/external_canister.rs, core/station/impl/src/models/request.rs, core/station/impl/src/models/request_operation.rs, core/station/impl/src/repositories/indexes/request_policy_resource_index.rs, core/station/impl/src/repositories/request.rs, core/station/impl/src/repositories/request_policy.rs, core/station/impl/src/services/external_canister.rs, libs/orbit-essentials/src/model.rs, tests/integration/src/external_canister_tests.rs, tests/integration/src/test_data/system_upgrade.rs
With the existing API it was not possible to optionally only update the ExternalCanister change or call request policies, we always had to provide both, same with the permissions for read, change, call. This PR updates that and marks the individual policy and permission types as optional.
=> feat(station): external canister input to accept opt policies and permissions by type

apps/wallet/src/components/external-canisters/CanisterInstallDialog.vue, apps/wallet/src/generated/station/station.did, apps/wallet/src/generated/station/station.did.d.ts, apps/wallet/src/generated/station/station.did.js, core/station/api/spec.did, core/station/api/src/external_canister.rs, core/station/impl/src/factories/requests/change_external_canister.rs, core/station/impl/src/mappers/request_operation.rs, core/station/impl/src/models/request_operation.rs, tests/integration/src/external_canister_tests.rs, tests/integration/src/system_upgrade_tests.rs, tests/integration/src/utils.rs, tools/dfx-orbit/src/args/request/canister.rs
This PR adds support for deploying external canisters with large WASM assembled from chunks stored in a dedicated asset canister.
=> feat(station): large WASM support for external canisters

Cargo.lock, core/station/impl/src/factories/requests/change_external_canister.rs, tests/integration/src/dfx_orbit.rs, tests/integration/src/dfx_orbit/install.rs, tests/integration/src/dfx_orbit/util.rs, tools/dfx-orbit/Cargo.toml, tools/dfx-orbit/src/canister.rs, tools/dfx-orbit/src/canister/install.rs
This PR fixes the computation of `module_checksum` for external canisters with large WASM in the station and adds support for large WASM in the dfx-orbit tool.
=> feat(dfx-orbit): support installing canisters with large WASM

.github/workflows/tests.yaml, Cargo.lock, Cargo.toml, core/station/impl/Cargo.toml, core/station/impl/src/core/validation.rs, core/station/impl/src/errors/blockchain_api.rs, core/station/impl/src/errors/factory.rs, core/station/impl/src/factories/blockchains/core.rs, core/station/impl/src/factories/blockchains/internet_computer.rs, core/station/impl/src/factories/requests/transfer.rs, core/station/impl/src/jobs/execute_created_transfers.rs, core/station/impl/src/models/account.rs, core/station/impl/src/models/asset.rs, core/station/impl/src/models/blockchain_standard.rs, core/station/impl/src/services/account.rs, core/station/impl/src/services/system.rs, core/station/impl/src/services/transfer.rs, scripts/run-integration-tests.sh, tests/integration/Cargo.toml, tests/integration/src/address_book_tests.rs, tests/integration/src/cycles_monitor_tests.rs, tests/integration/src/interfaces.rs, tests/integration/src/transfer_tests.rs, tests/integration/src/utils.rs
This PR adds ICRC-1 support for the station.
Adding the default ICP asset to an account now generates 2 addresses for the account: AccountIdentifier and ICRC-1 Account. They reference the same account in the ICP ledger.
=> feat(station): add ICRC-1 support

apps/wallet/src/components/external-canisters/CanisterSetupDialog.vue, apps/wallet/src/generated/station/station.did, apps/wallet/src/generated/station/station.did.d.ts, apps/wallet/src/generated/station/station.did.js, core/control-panel/api/src/user_station.rs, core/control-panel/impl/src/core/constants.rs, core/control-panel/impl/src/services/deploy.rs, core/station/api/spec.did, core/station/api/src/external_canister.rs, core/station/impl/results.yml, core/station/impl/src/mappers/request_operation.rs, core/station/impl/src/models/external_canister.rs, core/station/impl/src/models/request_operation.rs, core/station/impl/src/services/external_canister.rs, libs/orbit-essentials/src/cmc.rs, libs/orbit-essentials/src/lib.rs, libs/orbit-essentials/src/utils/cycles.rs, libs/orbit-essentials/src/utils/mod.rs, tests/integration/src/control_panel_tests.rs, tests/integration/src/external_canister_tests.rs
This PR allows to create external canisters on a subnet of choice when using the station to create an external canister. To support fiduciary subnet which has higher cycles consumption, the initial number of cycles used when creating a canister using the station has been increased.
=> feat(station): allow external canister creation on subnet of choice

scripts/run-integration-tests.sh, tests/integration/src/disaster_recovery_tests.rs, tests/integration/src/system_upgrade_tests.rs, tests/integration/src/test_data/system_upgrade.rs, tests/integration/src/utils.rs
This PR makes the integration tests run with a large station WASM so that we make sure to be ready for having a large station WASM in production.
=> chore(ci): run integration tests with large station WASM

libs/orbit-essentials/src/install_chunked_code.rs, tests/integration/src/utils.rs, tools/dfx-orbit/src/canister/install.rs
This PR prefixes wasm chunk hashes with a slash when storing/retrieving wasm chunks to/from an asset canister. The motivation for this change is that icx-asset [prefixes](https://github.com/dfinity/sdk/blob/064e4ff3e47006ec13b99b012a5e69f1a56577c4/src/canisters/frontend/icx-asset/src/commands/upload.rs#L31) file names with slashes and thus this PR ensures that wasm chunks can be uploaded using icx-asset.
=> fix(orbit-essentials): prefix wasm chunk hashes with slash in asset canister

Cargo.lock, Cargo.toml, apps/wallet/src/components/external-canisters/CanisterIcSettingsDialog.spec.ts, apps/wallet/src/components/external-canisters/CanisterIcSettingsDialog.vue, apps/wallet/src/components/external-canisters/CanisterIcSettingsForm.vue, apps/wallet/src/components/external-canisters/external-canisters.types.ts, apps/wallet/src/generated/station/station.did, apps/wallet/src/generated/station/station.did.d.ts, apps/wallet/src/generated/station/station.did.js, apps/wallet/src/locales/en.locale.ts, apps/wallet/src/locales/fr.locale.ts, apps/wallet/src/locales/pt.locale.ts, apps/wallet/src/pages/ExternalCanisterDetailPage.vue, core/station/api/spec.did, core/station/api/src/external_canister.rs, core/station/impl/src/factories/requests/configure_external_canister.rs, core/station/impl/src/mappers/external_canister.rs, core/station/impl/src/mappers/request_operation.rs, core/station/impl/src/models/request_operation.rs, tests/integration/Cargo.toml, tests/integration/src/rate_limiter.rs, tools/dfx-orbit/src/canister/settings.rs
This PR bumps ic-cdk to 0.16.0 (so that canister snapshots are supported), but keeps ic-cdk at 0.13.2 for integration tests (requirement of PocketIC library).
=> chore(control-panel,station,upgrader): bump ic-cdk to 0.16.0

apps/wallet/src/generated/control-panel/control_panel.did, apps/wallet/src/generated/control-panel/control_panel.did.d.ts, apps/wallet/src/generated/control-panel/control_panel.did.js, apps/wallet/src/generated/station/station.did, apps/wallet/src/generated/station/station.did.d.ts, apps/wallet/src/generated/station/station.did.js, core/control-panel/api/spec.did, core/control-panel/impl/src/services/registry.rs, core/station/api/spec.did, core/station/impl/src/mappers/request_operation.rs, core/station/impl/src/models/request_operation.rs, core/upgrader/api/spec.did, libs/orbit-essentials/src/install_chunked_code.rs, libs/orbit-essentials/src/types.rs, tests/integration/src/dfx_orbit/install.rs, tests/integration/src/system_upgrade_tests.rs, tests/integration/src/utils.rs, tools/dfx-orbit/src/canister/install.rs
This PR uses the asset canister native chunking for large WASM: the extra chunks are uploaded as a single (chunked) asset as opposed to uploading each chunk as a separate asset.
=> chore(orbit-essentials): use asset canister native chunking for large WASM

Cargo.lock, Cargo.toml, tests/integration/src/utils.rs
This PR bumps ic-agent, ic-utils, and dfinity/sdk dependencies to their more recent versions to fix a bug in dfx-orbit: chunks were not uploaded to the asset canister in the right order. The fix has been tested manually.
Also it means that we are using dfinity/sdk master branch with the repro fix now
=> chore(dfx-orbit): Update dependencies to use SDK master with repro fix

tools/dfx-orbit/src/asset/upload.rs, tools/dfx-orbit/src/asset/util.rs
This PR adds check to `verify asset upload`, that not only the argument matches, but in fact the asset canister has the proposed upload, i.e. a matching `batch_id` and `evidence` pair.
This fixes FOLLOW-1702
=> fix(dfx-orbit): Check that there is a matching asset upload proposal

apps/wallet/src/generated/station/station.did, apps/wallet/src/generated/station/station.did.d.ts, apps/wallet/src/generated/station/station.did.js, core/station/api/spec.did, core/station/api/src/request.rs, core/station/impl/src/controllers/request.rs, core/station/impl/src/errors/request.rs, core/station/impl/src/mappers/authorization.rs, core/station/impl/src/models/request.rs, core/station/impl/src/repositories/request.rs, core/station/impl/src/services/request.rs
Enables the requestor to cancel their own requests if those are still in the `Created` status.
=> feat(station): requestor can cancel pending requests

apps/wallet/src/components/external-canisters/CanisterSetupDialog.vue
BE otherwise rejects the creation of new external canister with "Missing field 'metadata'"
=> fix(station): add missing metadata field from UI

apps/wallet/src/components/system-upgrade/RegistryUpdateMode.vue, apps/wallet/src/components/system-upgrade/SystemUpgradeActionBtn.vue, apps/wallet/src/components/system-upgrade/system-upgrade.types.ts, cli/src/registry/publish.ts, cli/src/registry/registry.core.ts, cli/src/utils.ts, core/control-panel/impl/src/models/artifact.rs
Updates the control panel registry CLI script to operate with the large wasms, as well as, the frontend to correctly work if the control panel returns the large wasm information.
=> feat(enable): wallet ui accepts wasm chunk store from registry

apps/wallet/src/components/ui/ErrorCard.vue, apps/wallet/src/components/ui/ErrorDialog.vue
The default error dialog that is used when certain components fail to load was missing a close button (e.g. if the webassembly dependency for didc parsing fails to load), this change enables to user to continue to navigate in the user interface by closing it.
=> feat(wallet): add close btn to error dialog

apps/wallet/src/composables/request.composable.ts, apps/wallet/src/pages/RequestsPage.vue, core/station/impl/src/core/init.rs
Ensures that the capabilities of the station are only available to authenticated users, as well as, fixes a bug in the UI that was showing more request types in the Transfer Requests page.
=> fix(wallet): transfer requests page should only show transfers

apps/wallet/src/generated/station/station.did, apps/wallet/src/generated/station/station.did.d.ts, apps/wallet/src/generated/station/station.did.js, apps/wallet/src/pages/AccountAssetPage.vue, apps/wallet/src/services/station.service.ts, apps/wallet/src/workers/accounts.worker.ts, core/control-panel/impl/src/controllers/station.rs, core/station/api/spec.did, core/station/api/src/account.rs, core/station/impl/src/mappers/account.rs, core/station/impl/src/models/account.rs, core/station/impl/src/services/account.rs, libs/orbit-essentials/src/utils/lock.rs, tests/integration/src/account_tests.rs, tests/integration/src/lib.rs, tests/integration/src/transfer_tests.rs, tests/integration/src/utils.rs
At the moment concurrent calls to fetch the balances of the assets of an account result in all of them fetching the balances with inter canister calls.
If an account asset balance is getting queried concurrent calls should not result in additional balance queries, but those should return the last balance value.
=> perf(station): make concurrent balance queries more efficient

orbit, scripts/deploy.sh
This change enables us to drop the old unused wasm module from the the control panel, the new release process uses the asset chunk store instead.
=> fix(control-panel): fix initial station deploy

apps/wallet/src/core/compatibility.core.ts, apps/wallet/src/utils/helper.utils.spec.ts, apps/wallet/src/utils/helper.utils.ts
Ensures the semver compatibility layer correctly validates versions instead of simply doing a string comparison for latest api version.
=> fix(wallet): fix semver compatibility check

libs/orbit-essentials/src/cmc.rs, tests/integration/src/setup.rs
This PR updates the helper function for canister creation to always use CMC for canister creation: this way, stations created by the control panel and external canisters created by the station without specifying a subnet explicitly will be created at a (pseudo-)random application subnet instead of always creating those canisters on the same subnet. (The upgrader is still always created on the same subnet as its station.) This is supposed to achieve better load balancing. If external canisters need to be collocated, a subnet should be specified explicitly.
=> chore(control-panel,station): always use CMC for canister creation

.github/workflows/tests.yaml, README.md, dfx.json, orbit
This PR installs CMC ([proposal](https://dashboard.internetcomputer.org/proposal/134500)) in Orbit local deployments since CMC is required to create canisters (stations and external canisters). Additionally, this PR:
- updates README to use PocketIC as the local IC backend (to retrieve its topology at an HTTP endpoint not served by the replica) and stop it using `dfx stop` rather than by CTRL^C (due to an issue in dfx)
- updates dfx version (to include recent PocketIC serving its topology at an HTTP endpoint)
=> fix(ci): install CMC in Orbit local deployment

core/upgrader/api/spec.did, core/upgrader/impl/src/controllers/logs.rs, core/upgrader/impl/src/lib.rs, core/upgrader/impl/src/services/logger.rs
This PR removes the deprecated log API and stable memories in the upgrader, reducing its default stable memory footprint from 40MiB to 24MiB. The deprecated upgrader logs [do not get](https://github.com/dfinity/orbit/blob/7fd45ed6e053fdac2cea05f9807ab45a40244c06/core/upgrader/impl/src/services/logger.rs#L239) any new logs since the last upgrader [release](https://github.com/dfinity/orbit/releases/tag/%40orbit%2Fupgrader-v0.1.0) (end of Nov).
=> chore(upgrader): remove deprecated log API and stable storage

.github/workflows/tests.yaml, README.md, orbit
This PR adds support for local replica in addition to PocketIC for local deployment. The motivation is that PocketIC started by dfx doesn't properly support resuming a local deployment after `dfx stop`.
=> chore(ci): support local replica for local deployment

apps/wallet/src/components/accounts/TransferForm.vue, apps/wallet/src/components/inputs/AddressBookAutocomplete.spec.ts, apps/wallet/src/components/inputs/AddressInput.spec.ts, apps/wallet/src/components/inputs/AddressInput.vue, apps/wallet/src/components/request-policies/specifier/AddressBookEntrySpecifier.vue, apps/wallet/src/components/settings/StationInfoCard.vue, apps/wallet/src/composables/autocomplete.composable.ts, apps/wallet/src/generated/internet-identity/internet_identity.did, apps/wallet/src/generated/internet-identity/internet_identity.did.d.ts, apps/wallet/src/generated/internet-identity/internet_identity.did.js, apps/wallet/src/generated/station/station.did, apps/wallet/src/generated/station/station.did.d.ts, apps/wallet/src/generated/station/station.did.js, apps/wallet/src/pages/AddressBookPage.vue, apps/wallet/src/services/station.service.ts, apps/wallet/src/types/station.types.ts, core/station/api/spec.did, core/station/api/src/address_book.rs, core/station/impl/src/mappers/address_book.rs, core/station/impl/src/models/address_book.rs, core/station/impl/src/services/address_book.rs, tests/integration/src/address_book_tests.rs, tests/integration/src/migration_tests.rs
What changed:
`AddressBookAutocomplete` now lets you search and pick from the entire address book.
New component: AddressInput that lets you input an address, aided with autocomplete from the address book.
=> feat(wallet): searchable address book; pick from address book at transfer

core/upgrader/impl/src/model/disaster_recovery.rs
This PR optimizes stable memory serialization in the upgrader by using `#[serde(with = "serde_bytes")]` for WASM binaries and their args.
=> feat(upgrader): optimize stable memory serialization

core/upgrader/impl/src/services/disaster_recovery.rs, tests/integration/src/disaster_recovery_tests.rs, tests/integration/src/upgrader_test_data.rs
This PR ensures that only disaster recovery requests from current committee members are considered, i.e., requests from past committee members who left the committee are discarded.
=> fix(upgrader): only retain requests from current committee members

tests/integration/src/system_upgrade_tests.rs, tests/integration/src/upgrader_migration_tests.rs, tests/integration/src/utils.rs
This PR hardens upgrader stable memory migration tests by testing:
- stable memory size doesn't grow after upgrade;
- latest stable memory size structure (5 buckets of 8MiB each and stable structures header);
- stable memory can grow with the latest stable memory layout;
- the station can still be upgraded via the upgrader with the latest stable memory layout.
=> chore(upgrader): harden upgrader stable memory migration tests

core/upgrader/impl/src/lib.rs, core/upgrader/impl/src/services/disaster_recovery.rs, core/upgrader/impl/src/upgrade.rs
This PR simplifies upgrader code by assuming that target canister is always set in production and defaulting to anonymous principal in unit tests. This is a harmless assumption since an upgrader without a target canister set cannot be used and/or recovered.
=> chore(upgrader): assume that target canister is always set in production

apps/wallet/src/components/requests/OpenRequestOverlay.vue, apps/wallet/src/components/requests/PolicyRuleResultView.vue, apps/wallet/src/components/requests/RequestDetailView.spec.ts, apps/wallet/src/components/requests/RequestDetailView.vue, apps/wallet/src/components/requests/RequestDialog.spec.ts, apps/wallet/src/components/requests/RequestDialog.vue, apps/wallet/src/locales/en.locale.ts, apps/wallet/src/locales/fr.locale.ts, apps/wallet/src/locales/pt.locale.ts, apps/wallet/src/services/station.service.ts
When a request is pending approval the requester can cancel it from the request dialog.
=> feat(wallet): requesters can cancel their requests

core/control-panel/api/src/user_station.rs, core/control-panel/impl/src/controllers/canister.rs, core/control-panel/impl/src/controllers/http.rs, core/control-panel/impl/src/core/metrics.rs, core/control-panel/impl/src/mappers/user.rs, core/control-panel/impl/src/models/user.rs, core/control-panel/impl/src/services/canister.rs, core/control-panel/impl/src/services/user.rs, tests/integration/src/control_panel_tests.rs
This PR updates the rate limiting policy in the control panel to allow every user to deploy 2 stations per day (instead of 3 stations in total).
=> feat(control-panel): user can deploy 2 stations per day

.github/workflows/tests.yaml, Dockerfile
Fixes 2 issues:
1. pnpm doesnt work - https://github.com/nodejs/corepack/issues/612 -> solved by installing latest (pinned) corepack manually
2. deprecated `upload-artifact@v3` -> followed the [migration guide](https://github.com/actions/upload-artifact/blob/main/docs/MIGRATION.md) to update to @v4
=> fix(station): docker build

.github/workflows/tests.yaml, Dockerfile, apps/wallet/src/components/add-station/DeployStation.spec.ts, apps/wallet/src/components/add-station/DeployStation.vue, apps/wallet/src/generated/control-panel/control_panel.did, apps/wallet/src/generated/control-panel/control_panel.did.d.ts, apps/wallet/src/generated/control-panel/control_panel.did.js, apps/wallet/src/locales/en.locale.ts, apps/wallet/src/locales/fr.locale.ts, apps/wallet/src/locales/pt.locale.ts, apps/wallet/src/services/control-panel.service.ts, core/control-panel/api/spec.did, core/control-panel/api/src/user.rs, core/control-panel/impl/src/controllers/canister.rs, core/control-panel/impl/src/controllers/user.rs, core/control-panel/impl/src/core/config.rs, core/control-panel/impl/src/mappers/mod.rs, core/control-panel/impl/src/mappers/user.rs, core/control-panel/impl/src/models/user.rs, core/control-panel/impl/src/repositories/user.rs, core/control-panel/impl/src/services/user.rs, tests/integration/src/control_panel_tests.rs, tests/integration/src/cycles_monitor_tests.rs
This PR removes the waiting list and sets the stable memory version in `CanisterConfig::default()` so that memory migration is not triggered for upgrades from new control panel deployments.
=> feat(control-panel): remove waiting list

core/station/impl/src/services/system.rs, tests/integration/src/cycles_monitor_tests.rs
Ensures that if there is a source for cycles (e.g. ICP account), that the station and upgrader will be funded to a threshold that allows them to have the necessary amount of cycles for reservation for costly operations such as canister upgrades.
=> feat(station): update monitoring strategy

scripts/docker-build.sh
It appears that without specifying the platform docker uses the wrong image on mac, resulting in missing file error:
```
rosetta error: failed to open elf at /lib64/ld-linux-x86-64.so.2
```
=> fix(orbit): force platform linux/amd64 in docker build

core/station/impl/src/factories/requests/mod.rs, core/station/impl/src/factories/requests/system_upgrade.rs
This PR stops syncing station data to the upgrader after every upgrade of the upgrader. This is safe under the assumption that people don't use a recent station (containing this PR) to upgrade an old upgrader that did not contain any station data and thus syncing station data after an upgrade was necessary.
=> chore(station,upgrader): do not sync station data to upgrader after every upgrade of upgrader

core/station/api/src/external_canister.rs, core/station/impl/src/controllers/external_canister.rs, core/station/impl/src/controllers/mod.rs, core/station/impl/src/core/init.rs, core/station/impl/src/core/validation.rs, core/station/impl/src/mappers/authorization.rs, core/station/impl/src/models/request_operation.rs, core/station/impl/src/services/external_canister.rs, tests/integration/src/external_canister_tests.rs
This PR restricts access to reading canister snapshots/status for system canisters by using the permission `Resource::System(SystemResourceAction::SystemInfo)` instead of external canister permissions which are not appropriate for system canisters.
=> fix(station): restrict access to system canister info

core/station/impl/src/errors/request_execute.rs, core/station/impl/src/jobs/mod.rs, core/station/impl/src/models/request.rs, core/station/impl/src/services/request.rs, tests/integration/src/system_upgrade_tests.rs, tests/integration/src/utils.rs
This PR repeats request validation before execution to cover cases when the request becomes invalid while accepting votes.
=> chore(station): perform request validation before execution

core/station/impl/src/factories/requests/add_asset.rs, core/station/impl/src/factories/requests/edit_asset.rs, core/station/impl/src/factories/requests/remove_asset.rs
The asset related request factory implementations used custom request creation code which did not correctly instantiate the requests.
=> fix(station): Asset request factories now use Request::from_request_creation_input

core/station/impl/src/jobs/execute_created_transfers.rs, core/station/impl/src/jobs/execute_scheduled_requests.rs
This PR hardens async batch flows to not enumerate the results and index into foreign vectors since those foreign vectors might not be aligned with the result vector (it does not seem to be an issue at the moment, but the current design is error-prone w.r.t. future changes).
=> fix(station): harden async batch flows

core/station/impl/results.yml, rust-toolchain.toml, scripts/generate-wasm.sh
This PR bumps the Rust compiler version to the latest stable version 1.87.0 and the ic-wasm version to the latest version 0.9.3.
The performance improves quite a bit due to bulk memory operations (requiring the ic-wasm version bump).
=> chore(ci): bump Rust to 1.87.0

.github/workflows/validation.yaml, Cargo.lock, Cargo.toml, libs/orbit-essentials/Cargo.toml, libs/orbit-essentials/src/utils/random.rs, scripts/generate-wasm.sh
This PR bumps the `uuid` and `getrandom` crates. Because of
```
#[no_mangle]
unsafe extern "Rust" fn __getrandom_v03_custom(
```
multiple versions of the orbit essentials library in the build tree might lead to linking errors.
=> chore(ci): bump uuid crate

apps/wallet/src/utils/evaluation.utils.ts
This PR fixes the message "Request rejected for the following reasons: ." in case of no matching approval policy found to "Request rejected for the following reasons: No matching approval policy.".
=> fix(wallet): empty reason if no matching approval policy found
